---
# tasks file for Bind setup
- name: Install bind
  yum:
    pkg: bind
    state: latest

- name: Set hostname fact
  set_fact:
    ansible_fqdn: ns1.example.jp

- name: Copy named conf file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0660

- name: Make named directory
  file:
    path: /etc/named
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: 0640

- name: Make zones Directory
  file:
    path: /etc/named/zones
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/named/zones/db.example.jp
    owner: root
    group: named
    mode: 0640

- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/named/zones/db.79.168.192.in-addr.arpa
    owner: root
    group: named
    mode: 0640

- name: restart named
  service:
    name: named
    state: restarted
